#! /bin/sh

xinput --set-prop 'pointer:''Kingston HyperX Pulsefire Core' 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 'pointer:''Kingston HyperX Pulsefire Core' 'libinput Accel Speed' 0

xrandr --output HDMI-0 --mode 2560x1080 --rate 75

picom --experimental-backends -b
$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
dunst &
$HOME/.bin/arch-updates.sh &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         1
bspc config window_gap           12
bspc config normal_border_color  "#282828"
bspc config focused_border_color "#ebdbb2"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a jetbrains-idea-ce state=floating
bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Lutris state=floating
bspc rule -a VirtualBox Manager state=floating
bspc rule -a Gimp-2.10 desktop='^3' state=floating
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
